title: Alpha-video Staus
buildFuture: true
defaultContentLanguage: en
languageCode: en
baseURL: https://status.alpha-video.andrewstech.me/
params:
  disableDarkMode: false
  shortDateFormat: 15:04 — Jan 2
  down: "#e60000"
  systems:
    - name: youtube-dl
      category: system
      description: finds the streaming links
  dateFormat: January 2, 2006 at 3:04 PM
  brand: "#0a0c0f"
  headerTextColor: white
  logo: /logo.png
  incidentPostsPerPage: 10
  googleAnalytics: UA-00000000-1
  customTabs:
    - name: GITHUB
      link: https://github.com/unofficial-skills/alpha-video
    - name: Project Page
      link: https://alpha-video.andrewstech.me/
  alwaysKeepBrandColor: true
  disableComplexCalculations: false
  useLogo: false
  disrupted: "#cc4400"
  notice: "#24478f"
  incidentHistoryFormat: yearly
  disableIncidentHistory: true
  ok: "#008000"
  categories:
    - name: system
      untited: true
  description: We continuously monitor the status of our services and if there are
    any interruptions, a note will be posted here.
  enableCustomHTML: false
  useLargeHeaderDesign: true
theme: cstate
preserveTaxonomyNames: true
taxonomies:
  affected: affected
outputs:
  page:
    - html
    - json
  section:
    - html
    - json
    - rss
  home:
    - html
    - json
    - rss
    - svg
outputFormats:
  svg:
    isPlainText: true
    mediaType: image/svg+xml
